version: "3.3"

services:
  # Nginx
  nginx:
    build: ./nginx
    container_name: editor-nginx
    environment:
      - VIRTUAL_HOST=editorium.net
      - LETSENCRYPT_HOST=editorium.net
    depends_on:
      - nest
    expose:
      - 80
      - 443
    links:
      - nest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  nest:
    build: ./nest
    container_name: nest
    command: npm run start:dev
    restart: unless-stopped
    expose:
      - 3000

networks:
  editorium-network:
    driver: bridge
  default:
    external:
      name: nginx-proxy